### ISSUE TITLE
not emit close event

### ISSUE THREAD

**Issue by icymind** [roccomuso/netcat#7]
here is my code:
``` js
 const promise = new Promise((resolve, reject) => {
      const nc = new NetcatClient()
      let output = ''
      nc.addr('127.0.0.1').port(7777)
        .connect()
        .on('data', data => { output += data.toString('utf8') })
        .on('close', () => {
              myCallback()
              resolve()
        })
        .on('error', (err) => {
          reject(err)
        })
        .send(`\r\n\r\ndate\r\n\r\n`)

      setTimeout(() => {
        nc.close()
      }, 5000)
    })
    return promise
```

close event can not be detected sometimes, the promise waits for resolve/reject forever.
 I have to rewrite my code to:
```js
      setTimeout(() => {
        nc.close()
        myCallback()
        resolve()
      }, 5000)
```

**Comment by roccomuso** [comment]
The client doesn't close the connection if you set an on `data` listener.
In that case it emits the `close` event only if the server close the established connection.

```javascript
  var nc2 = new NetcatClient()
  nc2.addr('127.0.0.1').port(2593).connect().send('yoyo').on('data', function (d) {
   console.log(d.toString())
  }).on('close', function () {
    console.log('client got close event (because server closed)')
  })
```

Check out also the [wait](https://github.com/roccomuso/netcat#waittimems-or-waitms) method.
What do you want to achieve exactly? Can you paste also the server code to reproduce any issues?

**Comment by icymind** [comment]
thanks for your reply. 

There is no server code. I setup a virtualbox's virtual serial port listen at 7777 as a tcp server. I use it to execute command on my virtual machine (and got result from it) without ssh.

I have tried wait() before but it doesn't work, codes like:
```js
  var nc2 = new NetcatClient()
  nc2.addr('127.0.0.1').port(2593).connect().send('yoyo').on('data', function (d) {
   console.log(d.toString())
  }).on('close', function () {
    console.log('client got close event (because server closed)')
  })
  .wait(1000)
```

Now I place `.wait(1000)` between `connect` and `send`, it works. 

maybe `wait` method is  what I need.

**Comment by roccomuso** [comment]
You should put `wait`, before a connect.

**Comment by icymind** [comment]
ok, thanks.

**Comment by icymind** [comment]
sorry for the bothering. I use `wait` api to set a timeout, but the promise still waiting resolve/reject forever. Is there any way to close the connection by client side?
```js
  static serialExec (serialTcpPort, command, waitTime = 1000) {
    const promise = new Promise((resolve, reject) => {
      const nc = new NetcatClient()
      let output = ''
      nc.addr('127.0.0.1').port(serialTcpPort)
        .wait(waitTime)
        .connect()
        .on('close', () => {
          resolve(output)
        })
        .on('data', data => { output += data.toString('utf8') })
        .on('error', (err) => {
          reject(err)
        })
        .send(`\r\n\r\n${command}\r\n\r\n`)
    })
    return promise
  }
```

**Comment by roccomuso** [comment]
What do you mean with "not happens every time"? Probably the connection established with the server is not closed by the server and it's kept open.
Try to reproduce this issue with a nc server so we can better investigate what happen.

**Comment by icymind** [comment]
I can't reproduce it every time, and the client doesn't connect to a nc server. maybe it's not a bug of netcat.
