### ISSUE TITLE
Replace shortid with nanoid

### ISSUE THREAD

**Issue by killbillsbor** [roccomuso/netcat#8]
Hi!

Your package looks impressive! I think I've found a way how to improve it a little bit :) Please consider replacing `shortid` with [`nanoid`](https://github.com/ai/nanoid). There are no significant changes for users, but there are some critical benefits:
- `shortid` is not maintained anymore (and issue tracker has many important issues);
- `shortid` has a problem with a random generator ([issue](https://github.com/dylang/shortid/issues/70)) and ID uniformity ([issue](https://github.com/dylang/shortid/issues/85)). `nanoid` uses hardware random generator and has special uniformity tests ([docs](https://github.com/ai/nanoid#security));
- Also, `nanoid` is [10x times faster](https://github.com/ai/nanoid#benchmark) than `shortid`.

What do you think about this, @roccomuso?

Thanks!

**Comment by roccomuso** [comment]
ok, i might consider the switch..

**Comment by roccomuso** [comment]
done, thanks. It would be cool if we also manage to make the tests pass on Mac.
